# CN Project - Private DNS

# Listen on Mac 1's LAN address
listen-address=10.7.17.51

# Only answer DNS queries on the configured interface
interface=en0
bind-interfaces

# Project DNS records
address=/app.teamX.test/10.7.8.105
address=/api.teamX.test/10.7.8.105

# Don't read /etc/resolver or other local configuration
no-resolv

# Forward all other DNS queries to public DNS
server=8.8.8.8
server=1.1.1.1

# Cache DNS responses
cache-size=1000